INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Mercurio",4878, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Venus",12100, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Tierra",12756, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Marte",6787, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Júpiter",142984, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Saturno",120536, TRUE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Urano",51108, FALSE,1);
INSERT INTO PLANETS (name, diameter, has_rings,galaxy_id) VALUES ("Neptuno",49538, FALSE,1);